# name
name: Build and Release

# trigger
on:
  push:

# one or more jobs
jobs:
  greetings:
    runs-on: ubuntu-latest
    steps: 
      - id: s01
        run: echo "github ${{ github.ref_name }}"
      - run: echo "before " && ls -l
      - id: s02
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - id: s03
        run: echo "before " && ls -l
