# name
name: Build and Release

# trigger
on:
  push:

# one or more jobs
jobs:
  greetings:
    runs-on: ubuntu-latest
    steps: 
      - id: s01
        run: echo "github ${{ github.ref_name }}"
      #- run: echo "before " && ls -l
      - id: s02
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - id: s03
        uses: actions/checkout@v5
        #run: echo "after " && ls -l
      - id: s04
        run: npm i -g @angular/cli && npm ci && echo "Angular CLI installed"
    # fake error: echo "faking error" && exit 1
      - id: s05
        run: ng build  
      - id: s06
        run: echo "after build" && ls -l dist/countingbook/browser/
      - id: s07
        uses: nwtgck/actions-netlify@v3.0
        with:
            publish-dir: dist/countingbook/browser
            production-deploy: true
        env:
            netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}